### ISSUE TITLE
Create a dropdown for the navbar

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/Decentralised-Ticketing-Based-On-NFTs#6]
1. Find the Navbar.js file.
2. Create a dropdown menu under create event tab.
3. The menu should align with the color scheme.

**Comment by nitin1chandani** [comment]
can you show me the design or any example(pic)
,also you want drop down menu under create event tab ->past events login
somewhat like this?
If you can explain then it will be great!

**Comment by adityabisht02** [comment]
Sure, I will let you know by evening

**Comment by nitin1chandani** [comment]
Sure

**Comment by adityabisht02** [comment]
The dropdown should be minimalist like the one below , make it under the create event tab.
 As for the dropdown values , just put any random values for now I will change it later.

![image](https://user-images.githubusercontent.com/89146189/226390672-84235ead-297b-4ce9-9a4d-3f782d7894cd.png)
