### ISSUE TITLE
Adjust the ticket cards to be 1/4 width and with a 1/8 margin from both sides

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/Decentralised-Ticketing-Based-On-NFTs#8]
The cards are currently arranged as follows:

![image](https://user-images.githubusercontent.com/89146189/226680199-9e89562e-710a-4363-87d2-547afefdb209.png)

1. Find the TicketListing.js file in Organiser-> Tickets.
2. Change the ticket items to be 1/4 width of screen and the items should be at the center.

**Comment by omernadeem1070** [comment]
Hello, I can do this.

**Comment by peterjohnson1000** [comment]
Hi, if the issue is not yet assigned I am open for it.

**Comment by adityabisht02** [comment]
Hey, this issue has been resolved I'll be closing this
